// <auto-generated />
namespace SistemaAcademicoMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddCorreoDocenteToCurso : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCorreoDocenteToCurso));
        
        string IMigrationMetadata.Id
        {
            get { return "202510030117313_AddCorreoDocenteToCurso"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
